### ISSUE TITLE
Users in blacklisted groups fail to validate group membership

### ISSUE THREAD

**Issue by irconan** [Bcfg2/bcfg2#150]
Using the `gid_blacklist` option in `bcfg2.conf` to mask a subset of the machine's groups can result in users to appear as incorrect entries.

I have, for example:
```
gid_blacklist=1000-
```

If I now have a user such as:
```
user:x:1:1:user:/home/user:/bin/sh
```

and a group such as:
```
group:x:1001:user
```

User will now fail to validate due to having an incorrect supplemental group even though bcfg2 is configured to ignore said group.

**Comment by AlexanderS** [comment]
This was fixed with #151.
