### ISSUE TITLE
NagiosGen: doesn't include default-group.cfg

### ISSUE THREAD

**Issue by irconan** [Bcfg2/bcfg2#161]
When I generate nagiosgen.cfg it doesn't include the default-group.cfg file described in the documentation.

**Comment by jcftang** [comment]
I'm running into the same issue.

**Comment by jcftang** [comment]
Perhaps it's this that's break

https://github.com/Bcfg2/bcfg2/blob/712eba48fa9db0c560409e022f2365eda7ae3d6e/src/lib/Bcfg2/Server/Plugins/NagiosGen.py#L102
