### ISSUE TITLE
Pac-Packages backend does not handle dependencies

### ISSUE THREAD

**Issue by jsteel44** [Bcfg2/bcfg2#347]
Therefore dependencies are classed as "extra entries".

**Comment by jsteel44** [comment]
I've tried #354 (applied to both client and server) but still seeing dependencies under "extra entries". ie I've got bcfg2 to install "vim", yet "vim-runtime" is an extra entry.

$ pacman -Qi vim-runtime
Name            : vim-runtime
Required By     : vim
Install Reason  : Installed as a dependency for another package
[...]

**Comment by AlexanderS** [comment]
Did you regenerate the package cache? Either by removing the cache files or with `bcfg2-admin xcmd Packages.Refresh`?

**Comment by jsteel44** [comment]
Looks good after clearing the cache, thanks!
