### ISSUE TITLE
python2-django 1.9 error (1.7 works)

### ISSUE THREAD

**Issue by jsteel44** [Bcfg2/bcfg2#349]
In Arch, "python2-django 1.7.11" works fine, but when updating to "python2-django 1.9.8" I get the following which causes an Apache 500 error:
https://bpaste.net/show/b4f0be565a3a
Switching back to 1.7 fixes the issue.

**Comment by solj** [comment]
Which version of bcfg2 did you test with?

**Comment by jsteel44** [comment]
Latest git revision

**Comment by AlexanderS** [comment]
Can you enable DEBUG with:

```
[reporting]
django_settings = {'DEBUG': True}
```

in your `bcfg2-web.conf` (or `bcfg2.conf` if you do not have a `bcfg2-web.conf`).

The connection error most likely is the try to connect to a not configured smtp server to send a mail with the backtrace. The real error will be shown in the the web interface with DEBUG enabled.

**Comment by jsteel44** [comment]
OK thanks, here's the output:
https://bpaste.net/show/99a5dfcf73dc

**Comment by jsteel44** [comment]
I'm getting a very similar error, just the last few lines are different:
```
Exception Type: AttributeError at /grid
Exception Value: 'module' object has no attribute 'url'
```

**Comment by AlexanderS** [comment]
Ah the future templatetag library exists in 1.9 but does not contain the url tag. Should be fixed now, can you test again?

**Comment by jsteel44** [comment]
Yes looks good now thanks!
