### ISSUE TITLE
bcfg2-test return the error AttributeError: 'lxml.etree._Element' object has no attribute 'xdata'

### ISSUE THREAD

**Issue by indrik2000** [Bcfg2/bcfg2#359]
Test and trace http://pasted.co/2d07f52d
Bundle http://pasted.co/c4531f59
Properties http://pasted.co/d40fbbc3

**Comment by AlexanderS** [comment]
What version of bcfg2 do you use?

**Comment by indrik2000** [comment]
1.3.6

**Comment by AlexanderS** [comment]
Seems like you have [automatch](http://docs.bcfg2.org/server/plugins/connectors/properties.html#automatch) enabled.

**Comment by indrik2000** [comment]
Ooh. You are right. 'automatch = false'  solved the issue.
